# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
eletrodomesticos = Category.create(name: "Eletrodomésticos")
aspirador = Category.create(name: "Aspirador", parent: Eletrodómesticos)
batedeira = Category.create(name: "Batedeira", parent: Eletrodómesticos)
chapinha = Category.create(name: "Chapinha", parent: Eletrodómesticos)
enceradeira = Category.create(name: "Enceradeira", parent: Eletrodómesticos)
ferramenta = Category.create(name: "Ferramenta", parent: Eletrodómesticos)
fogao = Category.create(name: "Fogão", parent: Eletrodómesticos)
forno_microondas = Category.create(name: "Forno Microondas", parent: Eletrodómesticos)
freezer = Category.create(name: "Freezer", parent: Eletrodómesticos)
geladeira = Category.create(name: "Geladeira", parent: Eletrodómesticos)
liquidificador = Category.create(name: "Liquidificador", parent: Eletrodómesticos)
maquina_de_lavar_louca = Category.create(name: "Máquina de Lavar Louça", parent: Eletrodómesticos)
maquina_de_lavar_roupa = Category.create(name: "Máquina de Lavar Roupas", parent: Eletrodómesticos)
mixer = Category.create(name: "Mixer", parent: Eletrodómesticos)
secadora = Category.create(name: "Secadora", parent: Eletrodómesticos)
secador_de_cabelo = Category.create(name: "Secador de Cabelo", parent: Eletrodómesticos)
torradeira = Category.create(name: "Torradeira", parent: Eletrodómesticos)
<br>
eletronicos = Category.create(name: "Eletrônicos")
camera = Category.create(name: "Câmera Fotográfica", parent: eletronicos)
celular = Category.create(name: "Celular", parent: eletronicos)
dvd = Category.create(name: "DVD", parent: eletronicos)
impressora = Category.create(name: "Impressora", parent: eletronicos)
notebook = Category.create(name: "Notebook", parent: eletronicos)
pc = Category.create(name: "PC", parent: eletronicos)
radio = Category.create(name: "Rádio", parent: eletronicos)
roteador_wifi = Category.create(name: "Roteador Wifi", parent: eletronicos)
tablet = Category.create(name: "Tablet", parent: eletronicos)
telefone_fixo = Category.create(name: "Telefone Fixo", parent: eletronicos)
televisor = Category.create(name: "Televisão", parent: eletronicos)
videocassete = Category.create(name: "Videocassete", parent: eletronicos)
<br>
lampadas = Category.create(name: "Lâmpadas")
incandescente = Category.create(name: "Lâmpada Incandescente", parent: lampadas)
fluorescente = Category.create(name: "Lâmpada Fluorescente", parent: lampadas)
<br>
madeira = Category.create(name: "Madeira")
armario = Category.create(name: "Armário", parent: madeira)
banco = Category.create(name: "Banco", parent: madeira)
cristaleira = Category.create(name: "Cristaleira", parent: madeira)
gabinete = Category.create(name: "Gabinete", parent: madeira)
guarda_roupa = Category.create(name: "Guarda-Roupa", parent: madeira)
mesa = Category.create(name: "Mesa", parent: madeira)
moldura = Category.create(name: "Moldura", parent: madeira)
pallet = Category.create(name: "Palete", parent: madeira)
pedaco_de_madeira = Category.create(name: "Pedaços de Madeira", parent: madeira)
<br>
moveis = Category.create(name: "Móveis")
sofa = Category.create(name: "Sofá", parent: moveis)
<br>
plastico = Category.create(name: "Plástico")
garrafa_plastico = Category.create(name: "Garrafa Plástica", parent: plastico)
sacola_de_plastico = Category.create(name: "Sacos/Sacola Plástica", parent: plastico)
pote_plastico = Category.create(name: "Tapware/Recipiente Plástico", parent: plastico)
brinquedo = Category.create(name: "Brinquedo de Plástico", parent: plastico)
<br>
vidro = Category.create(name: "Vidro")
cacos = Category.create(name: "Cacos de Vidro", parent: vidro)
copo = Category.create(name: "Copo/Caneca de Vidro", parent: vidro)
espelho = Category.create(name: "Espelho", parent: vidro)
garrafa_de_vidro = Category.create(name: "Garrafa de Vidro", parent: vidro)
janela cacos = Category.create(name: "Janela", parent: vidro)
peca_de_vidro = Category.create(name: "Peça de Decoração de Vidro", parent: vidro)
pote = Category.create(name: "Pote/Recipiente de Vidro", parent: vidro)
<br>
metal = Category.create(name: "Metal")
barra = Category.create(name: "Barra de Metal", parent: metal)
copo = Category.create(name: "Copo de Vidro", parent: metal)
decoracao = Category.create(name: "Decoração em Metal", parent: metal)
ferramenta = Category.create(name: "Ferramentas", parent: metal)
fios = Category.create(name: "Fios de Cobre", parent: metal)
lata_de_tinta = Category.create(name: "Latas de Tinta", parent: metal)
tubos = Category.create(name: "Tubos em Metal", parent: metal)
<br>
tecidos = Category.create(name: "Tecido")
banho = Category.create(name: "Roupa de Banho", parent: tecidos)
cama = Category.create(name: "Roupa de Cama", parent: tecidos)
cobertor = Category.create(name: "Cobertor", parent: tecidos)
cortina = Category.create(name: "Cortina", parent: tecidos)
retalho = Category.create(name: "Retalhos", parent: tecidos)
roupas = Category.create(name: "Roupas", parent: tecidos)
tapete = Category.create(name: "Tapete", parent: tecidos)
<br>
papel = Category.create(name: "Papel")
caixa = Category.create(name: "Caixa de Papelão", parent: papel)
livro = Category.create(name: "Livro/Apostila", parent: papel)
pedaço = Category.create(name: "Pedaços de Papel", parent: papel)
revista = Category.create(name: "Revistas", parent: papel)
<br>
borracha = Category.create(name: "Borracha")
pneus_bicicleta = Category.create(name: "Pneu de Bicicleta", parent: borracha)
pneu_carro = Category.create(name: "Pneu de Automóvel", parent: borracha)
